name: heavenly_tribulation
description: A Xianxia genre RPG game mixed with Roguelike/Tycoon elements.
publish_to: "none"

version: 0.1.0-demo

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter

  meta: ^1.7.0

  # hive: ^2.0.4
  # hive_flutter: ^1.1.0

  flame:
    ^1.22.0
    # path: ../../flame/packages/flame
  flame_splash_screen: ^0.3.0

  hetu_script:
    path: ../../hetu-script/packages/hetu_script
  hetu_script_flutter:
    path: ../../hetu-script/packages/hetu_script_flutter

  samsara:
    path: ../../samsara-engine

  quiver: ^3.0.1+1
  change_case: ^2.0.1
  path_provider: ^2.0.8
  data_table_2: ^2.5.11
  window_manager: ^0.4.3
  gradient_widgets: ^0.6.0
  path: ^1.8.1
  async: ^2.8.2
  fast_noise: ^2.0.0
  flutter_platform_alert: ^0.6.1
  vector_math: ^2.1.4
  json5: ^0.8.2
  video_player_win: ^3.1.1
  provider: ^6.1.2
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  msix: ^3.16.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/

    - assets/mods/

    - assets/audio/
    - assets/audio/sound/
    - assets/audio/music/

    - assets/data/
    # - assets/data/maps/

    - assets/images/
    - assets/images/animation/
    - assets/images/animation/bear/
    # - assets/images/animation/beard/
    - assets/images/animation/boar/
    - assets/images/animation/default/
    - assets/images/animation/girl/
    - assets/images/animation/snake/
    - assets/images/animation/tiger/
    - assets/images/illustration/
    - assets/images/illustration/male/
    - assets/images/illustration/female/
    - assets/images/illustration/main/
    - assets/images/illustration/npc/
    - assets/images/illustration/old/
    - assets/images/illustration/story/
    - assets/images/illustration/young/
    - assets/images/illustration/
    - assets/images/battle/
    - assets/images/battle/scene/
    - assets/images/cultivation/
    - assets/images/cultivation/battlecard/
    - assets/images/cultivation/battlecard/illustration/
    - assets/images/cultivation/deckbuilding/
    - assets/images/cultivation/library/
    - assets/images/cultivation/time/
    - assets/images/cg/
    - assets/images/cg/ch01/
    - assets/images/icon/
    - assets/images/icon/skill/
    - assets/images/icon/status/
    - assets/images/item/
    - assets/images/item/consumable/
    - assets/images/item/material/
    - assets/images/item/support/
    - assets/images/location/
    - assets/images/location/city/
    - assets/images/location/site/
    - assets/images/object/
    - assets/images/object/animation/
    - assets/images/talent_tree/
    - assets/images/ui/
    - assets/images/weather/

    # - assets/locale/en/
    - assets/locale/zh/

    - assets/save/

    - scripts/game/
    - scripts/game/ai/
    - scripts/game/binding/
    - scripts/game/cardbattle/
    - scripts/game/entity/
    - scripts/game/entity/character/
    - scripts/game/entity/item/
    - scripts/game/entity/location/
    - scripts/game/entity/organization/
    - scripts/game/interaction/
    - scripts/game/name/
    - scripts/game/name/book/
    - scripts/game/name/character/
    - scripts/game/name/common/
    - scripts/game/name/consumable/
    - scripts/game/name/creature/
    - scripts/game/name/material/
    - scripts/game/name/organization/
    - scripts/game/name/place/
    - scripts/game/name/skill/
    - scripts/game/name/spell/
    - scripts/game/name/talisman/
    - scripts/game/name/zone/
    - scripts/game/quest/
    - scripts/game/tile/
    - scripts/game/world/

    - scripts/tutorial/
    - scripts/tutorial/l10n/
    # - scripts/tutorial/l10n/en/
    - scripts/tutorial/l10n/zh/

  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMonoCJKsc-Regular.otf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMonoDerivativePowerline.ttf
    - family: QIJIC
      fonts:
        - asset: assets/fonts/qijic.ttf
    - family: RuiZiYunZiKuLiBianTiGBK
      fonts:
        - asset: assets/fonts/RuiZiYunZiKuLiBianTiGBK-1.ttf

msix_config:
  display_name: Heavenly Tribulation
  publisher_display_name: Hetu Studio
  identity_name: hetu.dev
  msix_version: 1.0.0.0
  logo_path: E:\_dev\heavenly-tribulation\media\LOGO.ico
