name: heavenly_tribulation
description: A Xianxia genre RPG game mixed with Roguelike/Tycoon elements.
publish_to: "none"

version: 0.1.0-demo

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter

  meta: ^1.7.0

  # hive: ^2.0.4
  # hive_flutter: ^1.1.0

  flame:
    ^1.16.0
    # path: ../../flame/packages/flame
  flame_splash_screen: ^0.3.0

  hetu_script:
    path: ../../hetu-script/packages/hetu_script
  hetu_script_flutter:
    path: ../../hetu-script/packages/hetu_script_flutter

  samsara:
    path: ../../samsara_engine

  quiver: ^3.0.1+1
  change_case: ^2.0.1
  path_provider: ^2.0.8
  data_table_2: ^2.2.0
  window_manager: ^0.3.8
  gradient_widgets: ^0.6.0
  path: ^1.8.1
  async: ^2.8.2
  fast_noise: ^2.0.0
  flutter_platform_alert: ^0.5.1
  vector_math: ^2.1.4
  json5: ^0.8.0
  video_player_win: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/

    - assets/mods/

    - assets/audio/
    - assets/audio/sound_effect/
    - assets/audio/music/

    - assets/data/

    - assets/images/
    - assets/images/animation/
    - assets/images/avatar/
    - assets/images/avatar/male/
    - assets/images/avatar/female/
    - assets/images/avatar/main/
    - assets/images/avatar/old/
    - assets/images/avatar/teen/
    - assets/images/avatar/
    - assets/images/battle/
    - assets/images/battle/scene/
    - assets/images/card/
    - assets/images/card/deckbuilding/
    - assets/images/card/frame/
    - assets/images/card/illustration/
    - assets/images/card/library/
    - assets/images/card/poker/
    - assets/images/clock/
    - assets/images/icon/
    - assets/images/icon/item/
    - assets/images/icon/item/consumable/
    - assets/images/icon/item/material/
    - assets/images/icon/skill/
    - assets/images/icon/status/
    - assets/images/item/
    - assets/images/location/
    - assets/images/location/site/
    - assets/images/maze/
    - assets/images/weather/

    - assets/locale/en/
    - assets/locale/zh/

    - scripts/game/
    - scripts/game/ai/
    - scripts/game/binding/
    - scripts/game/cardgame/
    - scripts/game/dialog/
    - scripts/game/entity/
    - scripts/game/entity/character/
    - scripts/game/entity/character/creature/
    - scripts/game/entity/character/npc/
    # - scripts/game/entity/character/status_effect/
    - scripts/game/entity/effect/
    - scripts/game/entity/item/
    - scripts/game/entity/item/consumable/
    - scripts/game/entity/item/material/
    - scripts/game/entity/item/talisman/
    - scripts/game/entity/item/talisman/protect/
    - scripts/game/entity/item/talisman/weapon/
    - scripts/game/entity/location/
    - scripts/game/entity/organization/
    - scripts/game/entity/skill/
    - scripts/game/l10n/
    - scripts/game/maze/
    - scripts/game/name/
    - scripts/game/name/book/
    - scripts/game/name/character/
    - scripts/game/name/common/
    - scripts/game/name/consumable/
    - scripts/game/name/creature/
    - scripts/game/name/material/
    - scripts/game/name/organization/
    - scripts/game/name/place/
    - scripts/game/name/skill/
    - scripts/game/name/spell/
    - scripts/game/name/talisman/
    - scripts/game/name/zone/
    # - scripts/game/predefined/
    - scripts/game/quest/
    - scripts/game/tile/
    - scripts/game/world/

    - scripts/story/
    - scripts/story/l10n/

  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMonoCJKsc-Regular.otf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMonoDerivativePowerline.ttf
    - family: QIJIC
      fonts:
        - asset: assets/fonts/qijic.ttf
    - family: RuiZiYunZiKuLiBianTiGBK
      fonts:
        - asset: assets/fonts/RuiZiYunZiKuLiBianTiGBK-1.ttf
