name: cli_test
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  hetu_script:
    path: ../hetu-script/packages/hetu_script
  hetu_script_dev_tools:
    path: ../hetu-script/packages/hetu_script_dev_tools

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
