name: heavenly_tribulation
description: A Xianxia genre RPG game mixed with Roguelike/Tycoon elements.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  meta: ^1.7.0

  hetu_script:
    path: ../../../hetu-script/packages/hetu_script
  hetu_script_flutter:
    path: ../../../hetu-script/packages/hetu_script_flutter

  # hive: ^2.0.4
  # hive_flutter: ^1.1.0
  flame:
    ^1.0.0
    # path: ../../../flame/packages/flame
  # flame_ecs:
  #   path: ../packages/flame_ecs

  code_text_field: ^1.0.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  quiver: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon/
    - assets/images/character/
    - assets/images/weather/
    - assets/images/maze/
    - assets/images/interior/
    - assets/images/location/
    - assets/images/location/scene/
    - assets/images/avatar/male/
    - assets/images/avatar/female/

    - scripts/
    - scripts/game/
    - scripts/game/l10n/
    - scripts/game/l10n/zh_name/
    - scripts/game/data/
    - scripts/game/generator/
    - scripts/game/generator/random_names/
    - scripts/game/generator/random_names/data/
    - scripts/game/generator/random_names/data/alchemy/
    - scripts/game/generator/random_names/data/book/
    - scripts/game/generator/random_names/data/creature/
    - scripts/game/generator/random_names/data/dao/
    - scripts/game/generator/random_names/data/material/
    - scripts/game/generator/random_names/data/name/
    - scripts/game/generator/random_names/data/organization/
    - scripts/game/generator/random_names/data/place/
    - scripts/game/generator/random_names/data/shared/
    - scripts/game/generator/random_names/data/skill/
    - scripts/game/generator/random_names/data/talisman/
    - scripts/core/
    - scripts/core/l10n/
    - scripts/core/data/
    - scripts/core/entity/

  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMonoCJKsc-Regular.otf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMonoDerivativePowerline.ttf
