name: heavenly_tribulation
description: A Xianxia genre RPG game mixed with Roguelike/Tycoon elements.
publish_to: "none"

version: 0.1.0-demo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  meta: ^1.7.0

  hetu_script:
    path: ../../../hetu-script/packages/hetu_script
  hetu_script_flutter:
    path: ../../../hetu-script/packages/hetu_script_flutter

  # hive: ^2.0.4
  # hive_flutter: ^1.1.0
  flame:
    ^1.0.0
    # path: ../../../flame/packages/flame
  # flame_ecs:
  #   path: ../packages/flame_ecs

  code_text_field: ^1.0.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  quiver: ^3.0.1+1
  change_case: ^1.0.1
  data_table_2: ^2.2.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bg/
    - assets/images/icon/
    - assets/images/character/
    - assets/images/weather/
    - assets/images/maze/
    - assets/images/interior/
    - assets/images/location/
    - assets/images/location/site/
    - assets/images/avatar/
    - assets/images/avatar/male/
    - assets/images/avatar/female/

    - scripts/
    - scripts/game/
    - scripts/game/l10n/
    - scripts/game/l10n/zh/
    - scripts/game/l10n/en/
    - scripts/game/data/
    - scripts/game/generator/
    - scripts/game/generator/tilemap/
    - scripts/game/generator/attributes/
    - scripts/game/generator/name/
    - scripts/game/generator/name/alchemy/
    - scripts/game/generator/name/creature/
    - scripts/game/generator/name/material/
    - scripts/game/generator/name/character/
    - scripts/game/generator/name/organization/
    - scripts/game/generator/name/place/
    - scripts/game/generator/name/shared/
    - scripts/game/generator/name/skill/
    - scripts/game/generator/name/talisman/
    - scripts/core/
    - scripts/core/l10n/
    - scripts/core/data/
    - scripts/core/entity/

  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMonoCJKsc-Regular.otf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMonoDerivativePowerline.ttf
