name: heavenly_tribulation
description: A Xianxia genre RPG game mixed with Roguelike/Tycoon elements.
publish_to: 'none'

version: 0.1.0-demo

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter

  meta: ^1.7.0

  # hive: ^2.0.4
  # hive_flutter: ^1.1.0

  flame:
    ^1.2.0
    # path: ../../../flame/packages/flame
  flame_audio: ^1.2.0
  flame_splash_screen: ^0.1.0

  hetu_script:
    path: ../../../hetu-script/packages/hetu_script
  hetu_script_flutter:
    path: ../../../hetu-script/packages/hetu_script_flutter

  samsara:
    path: ../samsara

  code_text_field: ^1.0.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  quiver: ^3.0.1+1
  change_case: ^1.0.1
  path_provider: ^2.0.8
  data_table_2: ^2.2.0
  window_manager: ^0.2.5
  logger: ^1.1.0
  gradient_widgets: ^0.6.0
  path: ^1.8.1
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/

    - assets/audio/
    - assets/audio/music/

    - assets/images/
    - assets/images/avatar/
    - assets/images/avatar/female/
    - assets/images/avatar/male/
    - assets/images/battle/
    - assets/images/bg/
    - assets/images/cg/
    - assets/images/character/
    - assets/images/icon/
    - assets/images/icon/item/
    - assets/images/icon/skill/
    - assets/images/item/
    - assets/images/location/
    - assets/images/location/site/
    - assets/images/maze/
    - assets/images/weather/

    - scripts/game/
    - scripts/game/entity/
    - scripts/game/entity/character/
    - scripts/game/entity/character/companion/
    - scripts/game/entity/character/enemy/
    - scripts/game/entity/character/merchant/
    - scripts/game/entity/item/
    - scripts/game/entity/item/consumable/
    - scripts/game/entity/item/protect/
    - scripts/game/entity/item/skill/
    - scripts/game/entity/item/weapon/
    - scripts/game/quest/
    - scripts/game/maze/
    - scripts/game/name/
    - scripts/game/name/book/
    - scripts/game/name/character/
    - scripts/game/name/consumable/
    - scripts/game/name/creature/
    - scripts/game/name/material/
    - scripts/game/name/organization/
    - scripts/game/name/place/
    - scripts/game/name/spell/
    - scripts/game/name/shared/
    - scripts/game/name/skill/
    - scripts/game/name/talisman/
    - scripts/game/binding/
    - scripts/game/l10n/
    - scripts/game/l10n/en/
    - scripts/game/l10n/zh/
    - scripts/game/tile/
    - scripts/game/ai/

    - scripts/story/
    - scripts/story/binding/
    - scripts/story/data/
    - scripts/story/data/sandbox_story/
    - scripts/story/l10n/

  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMonoCJKsc-Regular.otf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMonoDerivativePowerline.ttf
